### ISSUE TITLE
Better error message when client doesn't support Creation WorkspaceEdit

### ISSUE THREAD

**Issue by bo-tato** [clojure-lsp/clojure-lsp#1448]
**Describe the bug**
"Create test" code action fails if I haven't already created the file `test/<namespace>/<filename>_test.clj`
And (I'm using neovim) I just get a unclear error message:
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:409: method "workspace/applyEdit":
...
```
I'm not sure if this is an issue in neovim's lsp handling, or in clojure-lsp, looking at the lsp log it seems that clojure-lsp tells it to do "workspace/applyEdit" on the _test.clj file, which doesn't exist so vim errors. 

**To Reproduce**
1. Open any clojure file in neovim with lsp setup
2. Run "code actions"
3. Pick option "create test for..."

**Expected behavior**
Maybe clojure-lsp or neovim should be creating the file if it doesn't exist, or at least returning a clear error message about what file is missing that we need to create

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
[DEBUG][2023-01-12 11:39:37] .../lua/vim/lsp.lua:1381	"LSP[clojure_lsp]"	"client.request"	1	"workspace/executeCommand"	{  arguments = { "file:///aoc/protohackers/src/protohackers/challenge2.clj", 9, 7 },  command = "create-test"}	<function 1>	1
[DEBUG][2023-01-12 11:39:37] .../vim/lsp/rpc.lua:285	"rpc.send"	{  id = 96,  jsonrpc = "2.0",  method = "workspace/executeCommand",  params = {    arguments = { "file:///aoc/protohackers/src/protohackers/challenge2.clj", 9, 7 },    command = "create-test"  }}
[DEBUG][2023-01-12 11:39:37] .../vim/lsp/rpc.lua:388	"rpc.receive"	{  id = 96,  jsonrpc = "2.0"}
[DEBUG][2023-01-12 11:39:37] .../vim/lsp/rpc.lua:388	"rpc.receive"	{  id = 8,  jsonrpc = "2.0",  method = "workspace/applyEdit"}
[DEBUG][2023-01-12 11:39:37] .../vim/lsp/rpc.lua:403	"server_request: callback result"	{  status = true}
[DEBUG][2023-01-12 11:39:47] .../vim/lsp/rpc.lua:388	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/cancelRequest",  params = {    id = 8  }}
[DEBUG][2023-01-12 11:39:47] .../vim/lsp/rpc.lua:388	"rpc.receive"	{  id = 9,  jsonrpc = "2.0",  method = "window/showDocument",  params = {    selection = {      ["end"] = {        character = 999999,        line = 999999      },      start = {        character = 0,        line = 0      }    },    takeFocus = true,    uri = "file:///aoc/protohackers/test/protohackers/challenge2_test.clj"  }}
[WARN][2023-01-12 11:39:47] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"window/showDocument"
[DEBUG][2023-01-12 11:39:47] .../vim/lsp/rpc.lua:403	"server_request: callback result"	{  err = {    code = -32601,    message = "MethodNotFound",    <metatable> = {      __tostring = <function 1>    }  },  status = true}
[DEBUG][2023-01-12 11:39:47] .../vim/lsp/rpc.lua:285	"rpc.send"	{  error = {    code = -32601,    message = "MethodNotFound",    <metatable> = {      __tostring = <function 1>    }  },  id = 9,  jsonrpc = "2.0"}
</pre>
</details>

**User details (please complete the following information):**
 - OS: [Ubuntu Linux]
 - Editor [nvim]
 - Version: 2022.12.09-15.51.10

**Comment by ericdallo** [comment]
@bo-tato, I took a look, and it seems to be a vim issue as they don't handle the creation of files via [workspace edits](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceEdit), I think we should check on server side not to send that if client doesn't support it, but would make this feature not work at all too.
Anyway, I'd be nice to support that in vim, feel free to open a issue on nvim for that

**Comment by ericdallo** [comment]
I'll leave this issue open so we should present a better error message from server side, but the feature won't work unless client supports creation of files via WorkspaceEdit

**Comment by bo-tato** [comment]
cool thanks! I opened an issue on nvim here https://github.com/neovim/neovim/issues/21925
Also I've been trying out emacs as it's CIDER seems better for clojure development, and there the create test has a minor bug. If you have unsaved changes in the buffer of the filename_test.clj in emacs, the create test action will insert badly in the middle. I assume clojure-lsp is telling it to write some text at some position in the file, based on what it sees in the filename_test.clj on disk, and emacs is applying that edit to the buffer which can be different from the file on disk? maybe clojure-lsp can tell it to just always write to the end of the buffer?

**Comment by ericdallo** [comment]
hum, maybe, would you mind open a issue detailing a simple repro?

**Comment by bo-tato** [comment]
sure it's a little confusing to describe, I hope with the screenshots it's clear what the issue is

**Comment by bo-tato** [comment]
this is such a small thing I don't know if to open a new issue for it, but when helping the neovim people address this I ran into a weird behaviour: https://github.com/neovim/neovim/issues/21925#issuecomment-1399247575
it seems if clojure-lsp sees "test" anywhere in the full path, it does not present the "create test" action. I made a user named "test2" and was quite confused for a bit why "create test" action wasn't showing up.
You can also see for example if you move your project into a folder named:
just_testing_some_project_ideas/my_project

clojure-lsp won't present the "create test" action
but if you rename the folder to just_some_project_ideas

**Comment by ericdallo** [comment]
Yeah, that's actually expected..
ATM there is no way we know we are or not in a test file, so we infer that if the ns or filename doesn't contain anything mention test we are not in a test file  😅
That's why test files we don't show the code action

**Comment by bo-tato** [comment]
on the neovim issue for this they say clojure-lsp isn't sending the correct params with applyEdit?
https://github.com/neovim/neovim/issues/21925

for the test file name, clojure-lsp knows the folder of the workspace? so it could check if there's test anywhere in the path after that, we're probably in a test file of the project and don't show the code action, but if it's in the path before like in user name or some parent folder name then don't take that into account?

**Comment by ericdallo** [comment]
@bo-tato I took a look again, and clojure-lsp sends the correct params but there is a case when source-paths not found, it could return `nil` [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/lib/src/clojure_lsp/refactor/transform.clj#L921), so you probably have source-paths misconfigured.

I'll return a error for that case on server side for a more detailed message

**Comment by ericdallo** [comment]
@bo-tato, it should be fixed on master the error message, now clojure-lsp won't emit workspace/applyEdits with null as params, this improves the error message to user but you still need to understand why isn 't working for you, probably wrong source-paths

**Comment by bo-tato** [comment]
hm I tried nightly and still get the same error in neovim, but I guess that's something that has to be fixed on neovim's side:
this is the relevant logs:
```
2023-01-26T14:22:57.862Z  WARN [clojure-lsp.shared:88] - couldn't read file:///home/user/foo/test/foo/bar_test.clj
2023-01-26T14:22:57.864Z  ERROR [clojure-lsp.server:116] - Conformation error {:clojure.spec.alpha/problems ({:path [:edit :error], :pred (clojure.core/fn [%] (clojure.core/contains? % :error)), :val
 {:changes {nil nil, "file:///home/user/foo/test/foo/bar_test.clj" [{:range {:start {:line 0, :character 0}, :end {:line 7, :character 25}}, :new-text "(ns foo.bar-test\n  (:require\n   [clojure.test
 :refer [deftest is]]\n   [foo.bar :as subject]))\n\n(deftest foo-test\n  (is (= true\n         (subject/foo))))"}]}}, :via [:lsp4clj.coercer/workspace-edit-params :lsp4clj.coercer/workspace-edit-or-
error :lsp4clj.coercer/response-error], :in [:edit]} {:path [:edit :changes :changes 0], :pred clojure.core/string?, :val nil, :via [:lsp4clj.coercer/workspace-edit-params :lsp4clj.coercer/workspace-
edit-or-error :lsp4clj.coercer/workspace-edit :lsp4clj.coercer/changes], :in [:edit :changes 0 0]} {:path [:edit :changes :changes 1], :pred clojure.core/coll?, :val nil, :via [:lsp4clj.coercer/works
pace-edit-params :lsp4clj.coercer/workspace-edit-or-error :lsp4clj.coercer/workspace-edit :lsp4clj.coercer/changes :lsp4clj.coercer/edits], :in [:edit :changes 0 1]} {:path [:edit :document-changes :
changes 0], :pred clojure.core/string?, :val nil, :via [:lsp4clj.coercer/workspace-edit-params :lsp4clj.coercer/workspace-edit-or-error :lsp4clj.coercer/workspace-edit :lsp4clj.coercer/changes], :in 
[:edit :changes 0 0]} {:path [:edit :document-changes :changes 1], :pred clojure.core/coll?, :val nil, :via [:lsp4clj.coercer/workspace-edit-params :lsp4clj.coercer/workspace-edit-or-error :lsp4clj.c
oercer/workspace-edit :lsp4clj.coercer/changes :lsp4clj.coercer/edits], :in [:edit :changes 0 1]}), :clojure.spec.alpha/spec :lsp4clj.coercer/workspace-edit-params, :clojure.spec.alpha/value {:edit {
:changes {nil nil, "file:///home/user/foo/test/foo/bar_test.clj" [{:range {:start {:line 0, :character 0}, :end {:line 7, :character 25}}, :new-text "(ns foo.bar-test\n  (:require\n   [clojure.test :
refer [deftest is]]\n   [foo.bar :as subject]))\n\n(deftest foo-test\n  (is (= true\n         (subject/foo))))"}]}}}}
2023-01-26T14:23:06.899Z  INFO [clojure-lsp.feature.clojuredocs:23] - [Clojuredocs] Refreshing clojuredocs cache took 15834ms.
2023-01-26T14:23:07.867Z  ERROR [clojure-lsp.server:120] - No reponse from client after 10 seconds while applying workspace-edit.
2023-01-26T14:23:07.868Z  INFO [clojure-lsp.server:126] - Requesting to show on editor the document {:uri "file:///home/user/foo/test/foo/bar_test.clj", :take-focus true, :range {:start {:line 0, :ch
aracter 0}, :end {:line 999999, :character 999999}}}
```
This is the error shown:
![2023-01-26-161218_642x434_scrot](https://user-images.githubusercontent.com/122528427/214872943-cf6addcf-23f6-494d-a850-3240060c9c61.png)

after `touch foo/test/foo/bar_test.clj` the "create test" action works fine without error

**Comment by ericdallo** [comment]
Could you provide the client<->server json communication?

**Comment by bo-tato** [comment]
here's the logs https://gist.github.com/bo-tato/31a38ee43e4dce1070ce4e064dd19282

**Comment by ericdallo** [comment]
That looks a log from nvim and not sure what clojure-lsp is really returning, could you start clojure-lsp with `--trace verbose` and get the [server logs](https://clojure-lsp.io/troubleshooting/#server-log)?

**Comment by bo-tato** [comment]
ah ok here's the verbose clojure-lsp log: https://gist.github.com/bo-tato/c3f3e693476125d75e13ffcb44403a97

**Comment by ericdallo** [comment]
I can't see the workspace/applyEdit request there, ah, my bad the correct command should be `clojure-lsp --trace-level verbose`, then try to repro the issue and paste the logs here

**Comment by bo-tato** [comment]
hm I'd seen trace was deprecated and --help said to use --trace-level so that log was of `clojure-lsp --trace-level verbose` I tried logging it again with clojure-lsp: https://gist.github.com/bo-tato/d131980515809fec67c661d71908a686
and nvim's lsp log: https://gist.github.com/bo-tato/7f956a697bbd12c51249ff1f15e9bca2

**Comment by zhming0** [comment]
The issue seems to be happening still. When create a test file, Neovim LSP client reports that the `workspace/applyEdit` method called with `nil` as parameter.

```
[DEBUG][2024-10-30 22:37:39] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  id = 15,  jsonrpc = "2.0",  method = "workspace/applyEdit"}
```

I am on Neovim `v0.10.2` and clojure-lsp `2024.08.05-18.16.00`.

**Comment by zhming0** [comment]
I made a fix to this problem: #1907. Until the fix is out, a workaround in neovim is: 

`capabilities.workspace.workspaceEdit.documentChanges = true`
