### ISSUE TITLE
Emacs find definition with required ClojureDart files only works after visited once

### ISSUE THREAD

**Issue by wkok** [clojure-lsp/clojure-lsp#1589]
**Describe the bug**

Emacs v29 has a built in LSP client eglot

Invoking `xref-find-definitions` using eglot does not navigate to a `required` namespace unless either:

- The required namespace is visited manually first at least once
- Or the required namespace is saved in `.cljc` extension instead of `.cljd`

**To Reproduce**
1. Clone the minimal reproducible example: `git clone https://github.com/wkok/hello.git`
2. Open `src/acme/main.cljd` using emacs+eglot (eglot starts & connects with clojure-lsp fine)
3. Move point to line 8, right after `register!`
4. Invoke `xref-find-definitions` _but nothing happpens_
5. Now manually open the file `src/acme/model.cljd` (visiting the file)
6. Repeat step 2 - 4 and notice the behaviour is as expected
7. Another way that everything works as expected the first time is if both `main.cljd` and `main.cljd` is renamed to `main.cljc` and `main.cljc`

**Expected behavior**
A new buffer for `src/acme/model.cljd` should open and point should be on the `(register!)` function, without having to visit the new namespace manually first

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
(:jsonrpc "2.0" :id 7 :result
          [(:range
            (:start
             (:line 7 :character 3)
             :end
             (:line 7 :character 18)))])
[client-request] (id:8) Tue Jun  6 08:33:33 2023:
(:jsonrpc "2.0" :id 8 :method "textDocument/definition" :params
          (:textDocument
           (:uri "file:///home/wkok/src/hello/src/acme/main.cljd")
           :position
           (:line 7 :character 18)))
[server-reply] (id:8) Tue Jun  6 08:33:33 2023:
(:jsonrpc "2.0" :id 8 :result nil)
</pre>
</details>

<details>
 <summary><b>Log - clojure-lsp</b></summary>
<pre>
2023-06-06T07:46:08.247Z  INFO [clojure-lsp.server:596] - [SERVER] Starting server...
2023-06-06T07:46:08.248Z  DEBUG [clojure-lsp.nrepl:21] - nrepl not found, skipping nrepl server start...
2023-06-06T07:46:08.249Z  INFO [clojure-lsp.server:483] - Initializing...
2023-06-06T07:46:08.788Z  INFO [clojure-lsp.db:65] - [DB] Reading transit analysis cache from /home/wkok/src/hello/.lsp/.cache/db.transit.json db took 537ms
2023-06-06T07:46:08.799Z  INFO [clojure-lsp.dep-graph:269] - :maintain-dep-graph 9ms
2023-06-06T07:46:08.918Z  INFO [clojure-lsp.classpath:103] - Finding classpath via `/home/linuxbrew/.linuxbrew/bin/clojure -A:test:dev -Spath`
2023-06-06T07:46:08.936Z  DEBUG [clojure-lsp.classpath:115] - Classpath found, paths:  ["test" "src" "/home/wkok/.m2/repository/org/clojure/clojure/1.11.1/clojure-1.11.1.jar" "/home/wkok/.gitlibs/libs/tensegritics/clojuredart/b3a3399f3a0425a97ef9d6c5a5f31aeee2ee3feb/clj/src" "/home/wkok/.gitlibs/libs/tensegritics/clojuredart/b3a3399f3a0425a97ef9d6c5a5f31aeee2ee3feb/clj/test" "/home/wkok/.gitlibs/libs/tensegritics/clojuredart/b3a3399f3a0425a97ef9d6c5a5f31aeee2ee3feb/resources" "/home/wkok/.m2/repository/org/clojure/core.specs.alpha/0.2.62/core.specs.alpha-0.2.62.jar" "/home/wkok/.m2/repository/org/clojure/spec.alpha/0.3.218/spec.alpha-0.3.218.jar" "/home/wkok/.m2/repository/org/clojure/java.classpath/1.0.0/java.classpath-1.0.0.jar" "/home/wkok/.m2/repository/org/clojure/tools.cli/1.0.206/tools.cli-1.0.206.jar" "/home/wkok/.m2/repository/org/clojure/tools.deps.alpha/0.12.1162/tools.deps.alpha-0.12.1162.jar" "/home/wkok/.m2/repository/org/slf4j/slf4j-simple/1.7.36/slf4j-simple-1.7.36.jar" "/home/wkok/.m2/repository/com/cognitect/aws/api/0.8.539/api-0.8.539.jar" "/home/wkok/.m2/repository/com/cognitect/aws/endpoints/1.1.12.150/endpoints-1.1.12.150.jar" "/home/wkok/.m2/repository/com/cognitect/aws/s3/814.2.1053.0/s3-814.2.1053.0.jar" "/home/wkok/.m2/repository/com/google/guava/guava/31.0.1-android/guava-31.0.1-android.jar" "/home/wkok/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar" "/home/wkok/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar" "/home/wkok/.m2/repository/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar" "/home/wkok/.m2/repository/org/apache/maven/maven-core/3.8.4/maven-core-3.8.4.jar" "/home/wkok/.m2/repository/org/apache/maven/maven-resolver-provider/3.8.4/maven-resolver-provider-3.8.4.jar" "/home/wkok/.m2/repository/org/apache/maven/resolver/maven-resolver-api/1.6.3/maven-resolver-api-1.6.3.jar" "/home/wkok/.m2/repository/org/apache/maven/resolver/maven-resolver-connector-basic/1.6.3/maven-resolver-connector-basic-1.6.3.jar" "/home/wkok/.m2/repository/org/apache/maven/resolver/maven-resolver-impl/1.6.3/maven-resolver-impl-1.6.3.jar" "/home/wkok/.m2/repository/org/apache/maven/resolver/maven-resolver-spi/1.6.3/maven-resolver-spi-1.6.3.jar" "/home/wkok/.m2/repository/org/apache/maven/resolver/maven-resolver-transport-file/1.6.3/maven-resolver-transport-file-1.6.3.jar" "/home/wkok/.m2/repository/org/apache/maven/resolver/maven-resolver-transport-http/1.6.3/maven-resolver-transport-http-1.6.3.jar" "/home/wkok/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.6.3/maven-resolver-util-1.6.3.jar" "/home/wkok/.m2/repository/org/clojure/data.xml/0.2.0-alpha6/data.xml-0.2.0-alpha6.jar" "/home/wkok/.m2/repository/org/clojure/tools.gitlibs/2.4.172/tools.gitlibs-2.4.172.jar" "/home/wkok/.m2/repository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar" "/home/wkok/.m2/repository/com/cognitect/http-client/1.0.110/http-client-1.0.110.jar" "/home/wkok/.m2/repository/org/clojure/core.async/1.5.644/core.async-1.5.644.jar" "/home/wkok/.m2/repository/org/clojure/data.json/2.4.0/data.json-2.4.0.jar" "/home/wkok/.m2/repository/org/clojure/tools.logging/1.2.1/tools.logging-1.2.1.jar" "/home/wkok/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar" "/home/wkok/.m2/repository/com/google/errorprone/error_prone_annotations/2.7.1/error_prone_annotations-2.7.1.jar" "/home/wkok/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar" "/home/wkok/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar" "/home/wkok/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar" "/home/wkok/.m2/repository/org/checkerframework/checker-compat-qual/2.5.5/checker-compat-qual-2.5.5.jar" "/home/wkok/.m2/repository/org/checkerframework/checker-qual/3.12.0/checker-qual-3.12.0.jar" "/home/wkok/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar" "/home/wkok/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar" "/home/wkok/.m2/repository/org/apache/httpcomponents/httpcore/4.4.13/httpcore-4.4.13.jar" "/home/wkok/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2-no_aop.jar" "/home/wkok/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar" "/home/wkok/.m2/repository/org/apache/maven/maven-artifact/3.8.4/maven-artifact-3.8.4.jar" "/home/wkok/.m2/repository/org/apache/maven/maven-builder-support/3.8.4/maven-builder-support-3.8.4.jar" "/home/wkok/.m2/repository/org/apache/maven/maven-model/3.8.4/maven-model-3.8.4.jar" "/home/wkok/.m2/repository/org/apache/maven/maven-model-builder/3.8.4/maven-model-builder-3.8.4.jar" "/home/wkok/.m2/repository/org/apache/maven/maven-plugin-api/3.8.4/maven-plugin-api-3.8.4.jar" "/home/wkok/.m2/repository/org/apache/maven/maven-repository-metadata/3.8.4/maven-repository-metadata-3.8.4.jar" "/home/wkok/.m2/repository/org/apache/maven/maven-settings/3.8.4/maven-settings-3.8.4.jar" "/home/wkok/.m2/repository/org/apache/maven/maven-settings-builder/3.8.4/maven-settings-builder-3.8.4.jar" "/home/wkok/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.3.4/maven-shared-utils-3.3.4.jar" "/home/wkok/.m2/repository/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0.jar" "/home/wkok/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.0/plexus-component-annotations-2.1.0.jar" "/home/wkok/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.26/plexus-interpolation-1.26.jar" "/home/wkok/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.5/org.eclipse.sisu.inject-0.3.5.jar" "/home/wkok/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.plexus/0.3.5/org.eclipse.sisu.plexus-0.3.5.jar" "/home/wkok/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.30/jcl-over-slf4j-1.7.30.jar" "/home/wkok/.m2/repository/org/clojure/data.codec/0.1.0/data.codec-0.1.0.jar" "/home/wkok/.m2/repository/org/eclipse/jetty/jetty-client/9.4.44.v20210927/jetty-client-9.4.44.v20210927.jar" "/home/wkok/.m2/repository/org/eclipse/jetty/jetty-http/9.4.44.v20210927/jetty-http-9.4.44.v20210927.jar" "/home/wkok/.m2/repository/org/eclipse/jetty/jetty-util/9.4.44.v20210927/jetty-util-9.4.44.v20210927.jar" "/home/wkok/.m2/repository/org/clojure/tools.analyzer.jvm/1.2.1/tools.analyzer.jvm-1.2.1.jar" "/home/wkok/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar" "/home/wkok/.m2/repository/org/codehaus/plexus/plexus-sec-dispatcher/2.0/plexus-sec-dispatcher-2.0.jar" "/home/wkok/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar" "/home/wkok/.m2/repository/org/eclipse/jetty/jetty-io/9.4.44.v20210927/jetty-io-9.4.44.v20210927.jar" "/home/wkok/.m2/repository/org/clojure/core.memoize/1.0.253/core.memoize-1.0.253.jar" "/home/wkok/.m2/repository/org/clojure/tools.analyzer/1.1.0/tools.analyzer-1.1.0.jar" "/home/wkok/.m2/repository/org/clojure/tools.reader/1.3.6/tools.reader-1.3.6.jar" "/home/wkok/.m2/repository/org/ow2/asm/asm/5.2/asm-5.2.jar" "/home/wkok/.m2/repository/org/codehaus/plexus/plexus-cipher/2.0/plexus-cipher-2.0.jar" "/home/wkok/.m2/repository/org/codehaus/plexus/plexus-utils/3.4.1/plexus-utils-3.4.1.jar" "/home/wkok/.m2/repository/org/clojure/core.cache/1.0.225/core.cache-1.0.225.jar" "/home/wkok/.m2/repository/org/clojure/data.priority-map/1.1.0/data.priority-map-1.1.0.jar"]
2023-06-06T07:46:08.937Z  INFO [clojure-lsp.source-paths:85] - [Startup] Using source-paths from classpath: ["/home/wkok/src/hello/test" "/home/wkok/src/hello/src"]
2023-06-06T07:46:08.937Z  INFO [clojure-lsp.startup:114] - Copying kondo configs from classpath to project if any...
2023-06-06T07:46:08.994Z  WARN [clojure-lsp.kondo:328] - Non-fatal error from clj-kondo: Configs copied:
- .clj-kondo/tensegritics/clojuredart

2023-06-06T07:46:08.994Z  INFO [clojure-lsp.startup:116] - Copied kondo configs, took 57ms secs.
2023-06-06T07:46:08.995Z  INFO [clojure-lsp.startup:86] - Analyzing classpath for project root /home/wkok/src/hello
2023-06-06T07:46:08.995Z  INFO [clojure-lsp.kondo:355] - No new paths to analyze
2023-06-06T07:46:08.995Z  INFO [clojure-lsp.startup:101] - External classpath paths analyzed, took 0ms
2023-06-06T07:46:08.996Z  INFO [clojure-lsp.dep-graph:269] - :maintain-dep-graph 0ms
2023-06-06T07:46:09.097Z  INFO [clojure-lsp.startup:107] - Manual GC after classpath scan took 101ms
2023-06-06T07:46:09.097Z  INFO [clojure-lsp.startup:248] - Caching db for next startup...
2023-06-06T07:46:09.097Z  INFO [clojure-lsp.startup:261] - [Startup] Analyzing source paths for project root /home/wkok/src/hello
2023-06-06T07:46:09.097Z  INFO [clojure-lsp.startup:75] - [Startup] Project only paths analyzed by clj-depend, took 0ms
2023-06-06T07:46:09.099Z  INFO [clojure-lsp.dep-graph:269] - :maintain-dep-graph 0ms
2023-06-06T07:46:09.100Z  INFO [clojure-lsp.kondo:217] - Linting whole project for unused-public-var took 1ms
2023-06-06T07:46:09.100Z  WARN [clojure-lsp.kondo:328] - Non-fatal error from clj-kondo: No configs copied.

2023-06-06T07:46:09.100Z  INFO [clojure-lsp.startup:71] - [Startup] Project only paths analyzed by clj-kondo, took 3ms
2023-06-06T07:46:09.101Z  INFO [clojure-lsp.dep-graph:269] - :maintain-dep-graph 0ms
2023-06-06T07:46:09.102Z  INFO [clojure-lsp.handlers:171] - [Startup] Analyzing test paths for project root file:///home/wkok/src/hello
2023-06-06T07:46:09.102Z  INFO [clojure-lsp.feature.clojuredocs:21] - [Clojuredocs] Refreshing clojuredocs cache...
2023-06-06T07:46:09.102Z  INFO [clojure-lsp.handlers:149] - :initialize 852ms
2023-06-06T07:46:09.102Z  ERROR [clojure-lsp.db:72] - [DB] No cache DB file found
2023-06-06T07:46:09.102Z  INFO [clojure-lsp.db:65] - [DB] Reading transit analysis cache from /home/wkok/.cache/clojure-lsp/db.transit.json db took 0ms
2023-06-06T07:46:09.103Z  WARN [clojure-lsp.feature.java-interop:292] - [Java] Skipping download JDK source, setting `:java :download-jdk-source?` is disabled.
2023-06-06T07:46:09.103Z  WARN [clojure-lsp.feature.java-interop:303] - [Java] JDK source not found, skipping java analysis.
2023-06-06T07:46:09.105Z  INFO [clojure-lsp.server:505] - Initialized!
2023-06-06T07:46:09.115Z  INFO [clojure-lsp.dep-graph:269] - :maintain-dep-graph 0ms
2023-06-06T07:46:09.116Z  WARN [clojure-lsp.kondo:328] - Non-fatal error from clj-kondo: No configs copied.

2023-06-06T07:46:09.116Z  INFO [clojure-lsp.dep-graph:269] - :maintain-dep-graph 0ms
2023-06-06T07:46:09.117Z  INFO [clojure-lsp.handlers:179] - :did-open 11ms
2023-06-06T07:46:09.117Z  WARN [clojure-lsp.server:401] - {:settings {}}
2023-06-06T07:46:09.142Z  INFO [clojure-lsp.server:102] - :publish-diagnostics 0ms
2023-06-06T07:46:09.623Z  INFO [clojure-lsp.handlers:411] - :signature-help 1ms
2023-06-06T07:46:09.624Z  INFO [clojure-lsp.handlers:405] - :hover 1ms
2023-06-06T07:46:09.624Z  INFO [clojure-lsp.handlers:281] - :document-highlight 0ms
2023-06-06T07:46:09.750Z  INFO [clojure-lsp.feature.clojuredocs:23] - [Clojuredocs] Refreshing clojuredocs cache took 648ms.
2023-06-06T07:46:10.007Z  INFO [clojure-lsp.db:51] - [DB] Upserting transit analysis to /home/wkok/src/hello/.lsp/.cache/db.transit.json cache took 910ms
2023-06-06T07:46:17.110Z  INFO [clojure-lsp.handlers:281] - :document-highlight 0ms
2023-06-06T07:46:17.111Z  INFO [clojure-lsp.handlers:411] - :signature-help 1ms
2023-06-06T07:46:17.113Z  INFO [clojure-lsp.handlers:405] - :hover 3ms
2023-06-06T07:46:18.148Z  INFO [clojure-lsp.handlers:411] - :signature-help 2ms
2023-06-06T07:46:18.148Z  INFO [clojure-lsp.handlers:281] - :document-highlight 0ms
2023-06-06T07:46:18.149Z  INFO [clojure-lsp.handlers:405] - :hover 1ms
2023-06-06T07:46:20.317Z  INFO [clojure-lsp.handlers:250] - :definition 0ms

</pre>
</details>

**User details (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Editor Emacs 29.0.91
 - Version: clojure-lsp 2023.05.04-19.38.01

**Comment by ericdallo** [comment]
@wkok that's a bug in clj-kondo, I opened a [PR there](https://github.com/clj-kondo/clj-kondo/pull/2106), after fixing, we can bump on clojure-lsp and should be fixed

**Comment by wkok** [comment]
Thank you for looking into it!

**Comment by wkok** [comment]
Thanks, I installed from master / nightly:
```
$ clojure-lsp --version
clojure-lsp 2023.06.12-12.20.09-nightly
clj-kondo 2023.06.02-SNAPSHOT

```
unfortunately it's still not working -  without first navigating to the required namespace

**Comment by ericdallo** [comment]
It should be updated [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/lib/deps.edn#L11), I can take a closer look and test again soon

**Comment by wkok** [comment]
I have cleared all my caches, re-installed everything and can confirm this is indeed working now. 

Thanks!
